global:
  externalUrl: http://minikube.data.gov.au:30100
  rollingUpdate:
    maxUnavailable: 1
  exposeNodePorts: true
  image:
    repository: "localhost:5000/data61"
    tag: "latest"
    pullPolicy: Always
  noDbAuth: true
  useCloudSql: false
  useCombinedDb: true
  enablePriorityClass: false
  defaultContactEmail: "magda@mailinator.com"

gateway:
  ckanRedirectionDomain: "ckan.data.gov.au"
  ckanRedirectionPath: ""
  enableCkanRedirection: true
  enableAuthEndpoint: true
  arcgisInstanceBaseUrl: "https://beta.portal.data.nsw.gov.au/arcgis"
  cors:
    credentials: true
    origin: true
  auth:
    facebookClientId: "173073926555600"
    arcgisClientId: "xU0LNIvRZS2VUbFS"
    googleClientId: "275237095477-f7ej2gsvbl2alb8bcqcn7r5jk0ur719p.apps.googleusercontent.com"
    ckanAuthenticationUrl: https://data.gov.au/data

registry-api:
  skipAuthorization: false
  recordPolicyId: "object.registry.record.esri_groups"
  
correspondence-api:
  smtpPort: 2525
  smtpHostname: "smtp.mailgun.org"
  
web-server:
  fallbackUrl: "https://data.gov.au"
  featureFlags:
    cataloguing: true

connectors:
  includeCronJobs: false
  config:
    - image:
        name: "magda-esri-portal-connector"
      id: esri-nsw
      name: "beta.portal.data.nsw.gov.au/arcgis"
      sourceUrl: "https://beta.portal.data.nsw.gov.au/arcgis"
      pageSize: 1000
      registryUrl: "http://registry-api"
      arcgisUserId: "xxxxx"
      arcgisUserPassword: "xxxxx"
      userId: "00000000-0000-4000-8000-000000000000"
      schedule: "0 * * * *"
      ignoreHarvestSources: ["*"]
