global:
  externalUrl: http://minikube.data.gov.au:30100
  rollingUpdate:
    maxUnavailable: 1
  exposeNodePorts: true
  image:
    repository: "localhost:5000/data61"
    tag: "latest"
    pullPolicy: Always
  noDbAuth: true
  useCloudSql: false
  useCombinedDb: true
  enablePriorityClass: false
  defaultContactEmail: "magda@mailinator.com"
  enableMultiTenants: false

gateway:
  ckanRedirectionDomain: "ckan.data.gov.au"
  ckanRedirectionPath: ""
  enableCkanRedirection: false
  enableAuthEndpoint: true
  cors:
    credentials: true
    origin: true
  auth:
    facebookClientId: "173073926555600"
    arcgisClientId: "d0MgVUbbg5Z6vmWo"
    googleClientId: "275237095477-f7ej2gsvbl2alb8bcqcn7r5jk0ur719p.apps.googleusercontent.com"
    ckanAuthenticationUrl: https://data.gov.au/data

registry-api:
  skipAuthorization: false

correspondence-api:
  smtpPort: 2525
  smtpHostname: "smtp.mailgun.org"

web-server:
  fallbackUrl: "https://data.gov.au"
  featureFlags:
    cataloguing: true

connectors:
  includeCronJobs: false
  config:
    - image:
        name: "magda-ckan-connector"
      id: dga
      name: "data.gov.au"
      sourceUrl: "https://data.gov.au/"
      pageSize: 1000
      schedule: "0 * * * *"
      ignoreHarvestSources: ["*"]
