image: {}
  #repository: data61/
  #tag: latest
  #pullPolicy: Always#
autoscaler:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
resources:
  requests:
    cpu: 10m
    memory: 30Mi
  limits:
    cpu: 100m
disableAuthenticationFeatures: false
service: {}
useLocalStyleSheet: false
contentApiBaseUrlInternal: "http://content-api/v0/"
featureFlags: {}
vocabularyApiEndpoints: []
defaultContactEmail: "mail@example.com"
custodianOrgLevel: 2
maxChartProcessingRows: 20000
maxTableProcessingRows: 200
# default chunk size 2MB
csvLoaderChunkSize: 2097152
serverBasePath: "/"
